### ISSUE TITLE
Keep seeing the "Welcome to Genmon" popup after updating to 2.0.1

### ISSUE THREAD

**Issue by ashokaiyar** [jgyates/genmon#1450]
### Steps to Reproduce

I updated to 2.0.1, and every time I load the Genmon URL, I see this popup. I can "skip" it or go through all 4 screens, but it is back the next time I log into Genmon. How do I prevent that from happening?

<img width="536" height="229" alt="Image" src="https://github.com/user-attachments/assets/f41ac061-f84d-4dfc-9d9e-acb5af7044ed" />

### Expected Result

I should be able to dismiss this popup permanently. I didn't get it with 2.0.0

### Actual Result

Popup cannot be permanently dismissed

### Version Info

2.0.1

**Comment by jgyates** [comment]
If you continue to see this message that means your settings are not being saved in the /etc/genmon/genmon.conf file or it is being overwritten. The web interface will display this if the new UI settings are not present. Once it is displayed it will save the settings to the config file.

You did not include info on your environment or mention that if you have previously installed 2.0.0. If you are using a docker imange make sure that the file /etc/genmon/genmon.conf is saved. Did you install via the install script?

**Comment by ashokaiyar** [comment]
I had installed 2.0.1 over 2.0.0, which was installed over the previous version (1.2.0?). I'm running genmon on an RPi and not within Docker.

I installed the update to 2.0.1 using the web GUI, not the install script.

**Comment by jgyates** [comment]
Did you see the issue with 2.0.0 or is this new for 2.0.1? What browers and OS version are you using? Do you see any errors in the file /var/log/genserv.log?

**Comment by ashokaiyar** [comment]
It's new to 2.0.1.

Browsers: Safari 26.3.1
OS: MacOS Tahoe 26.3.1

Yes, there is an error in /var/log/genserv.log. Here are  the errors (the time corresponds to when I updated 2.0.0 to 2.0.1 using the GUI):

026-05-18 16:44:22,833 : Script: /bin/bash /home/genmonpi/genmon/startgenmon.sh restart -c /etc/genmon/
2026-05-18 16:44:32,655 : Error in WriteValue: 'NoneType' object has no attribute 'lower' : myconfig.py:248
2026-05-18 16:44:32,662 : Error in WriteValue: File contains no section headers.

**Comment by ashokaiyar** [comment]
I just noticed. I have also lost the "SiteName", and am unable to set the SiteName. It saves, but will not take/display the new Site Name. 

Same for the Weather Tile. It is no longer displayed. My API key and information is no longer there. I added the API key and location information again, but like the SiteName, it does not take or get used to display a weather tile.

**Comment by jgyates** [comment]
I am guessing you have a corrupted config file. You SD card could be failing or a corrupt file system. You could restore your settings from a previous backup if you have one. If not you could run this command to restore all of your config files to the default.

From the genmon folder:

     ./genmonmaint.sh -s

Then restart

     ./startgenmon.sh restart

Then try to save your settings again.

**Comment by ashokaiyar** [comment]
Thank you! That fixed it!! 

I have an industrial microSD, but I'll go ahead and get a second one and make a backup!
